# Generated by Django 4.0.4 on 2022-05-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_code',
        ),
    ]
