# Generated by Django 4.0.4 on 2022-05-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_location_location_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='categoryName',
        ),
    ]
