# Generated by Django 4.0.4 on 2022-05-29 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_category_image_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='categoryName',
        ),
        migrations.AddField(
            model_name='image',
            name='categoryName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.category'),
            preserve_default=False,
        ),
    ]
