# Generated by Django 4.0.4 on 2022-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_image_categoryname_image_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cat_name',
        ),
    ]
